
Traceback (most recent call last):

> File "tests/exceptions/backtrace/enqueue_with_others_handlers.py", line 19, in <module>
    1 / 0

ZeroDivisionError: division by zero
