
Traceback (most recent call last):
> File "tests/exceptions/backtrace/frame_values_forward.py", line 23, in <module>
    c(k)
  File "tests/exceptions/backtrace/frame_values_forward.py", line 20, in c
    b(n - 1)
  File "tests/exceptions/backtrace/frame_values_forward.py", line 15, in b
    a(n - 1)
  File "tests/exceptions/backtrace/frame_values_forward.py", line 11, in a
    1 / n
ZeroDivisionError: division by zero
