
Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 31, in <module>
    a(1)
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 1
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/backtrace/raising_recursion.py", line 31, in <module>
    a(1)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 32, in <module>
    a(2)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 2
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 1
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 32, in <module>
    a(2)
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 2
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/backtrace/raising_recursion.py", line 32, in <module>
    a(2)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 33, in <module>
    a(3)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 3
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 2
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 1
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 33, in <module>
    a(3)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 3
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 2
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 33, in <module>
    a(3)
    └ <function a at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 11, in a
    a(n - 1)
    │ └ 3
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/backtrace/raising_recursion.py", line 33, in <module>
    a(3)
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 12, in a
    n / 0
    └ 3

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 35, in <module>
    b(1)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 1
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 35, in <module>
    b(1)
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 36, in <module>
    b(2)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 2
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 1
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 36, in <module>
    b(2)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 2
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 36, in <module>
    b(2)
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 37, in <module>
    b(3)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 3
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 2
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 1
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 37, in <module>
    b(3)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 3
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 2
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 37, in <module>
    b(3)
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 18, in b
    b(n - 1)
    │ └ 3
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 37, in <module>
    b(3)
    └ <function b at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 19, in b
    n / 0
    └ 3

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 39, in <module>
    c(1)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 1
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 39, in <module>
    c(1)
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 40, in <module>
    c(2)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 2
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 1
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 40, in <module>
    c(2)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 2
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 40, in <module>
    c(2)
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 41, in <module>
    c(3)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 3
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 2
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 1
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 41, in <module>
    c(3)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 3
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 2
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 1

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 41, in <module>
    c(3)
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/raising_recursion.py", line 25, in c
    c(n - 1)
    │ └ 3
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 2

ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/backtrace/raising_recursion.py", line 41, in <module>
    c(3)
    └ <function c at 0xDEADBEEF>

> File "tests/exceptions/backtrace/raising_recursion.py", line 26, in c
    n / 0
    └ 3

ZeroDivisionError: division by zero
